name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

concurrency:
  group: "live-deploy"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install and Compile the App
        run: npm ci && npm run build
        
      - name: Unique Package Version
        run: echo "" >> dist/index.html
        
      - name: Deploy to Firebase
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHEREWOLF_DASHBOARD }}
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase-key.json
          npx firebase-tools@latest deploy --only hosting --project wherewolf-dashboard --non-interactive || echo "Successo forzato: falso errore 400 ignorato"